services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    container_name: "postgres-container"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
